env:
  global:
    - GIT_AUTHOR_NAME: Antonios Karagiannis
    - GIT_AUTHOR_EMAIL: antokarag@gmail.com
    - GIT_COMMITTER_NAME: Antonios Karagiannis
    - GIT_COMMITTER_EMAIL: antokarag@gmail.com
language: node_js
node_js:
  - 10.16.3
stages:
  - lint
  - test
  - build
  - name: deploy
    if: branch = master AND type = push
jobs:
  include:
    - stage: lint
      script:
        - npm run cl
        - npm run prettier
        - npm run lint
        - npm run ts:validate
    - stage: test
      script:
        - npm run test:cov
        - npm run coveralls
    - stage: build
      script:
        - npm run build
    - stage: deploy
      script:
        - npm run build
      deploy:
        skip_cleanup: true
        provider: s3
        bucket: spsa.church-production
        region: us-east-2
        local_dir: dist
        access_key_id:
          secure: 'B/xWaGytf/v4H4iCQS+wpklfu2yT/1oOvCaw3s2v7fyWfxfpPXtF+tSQmafcSshpcM61cd0zU2UfIV8pPq8dOzvM6HcyHLHiQ0zIK2pBeT6NN3cnkMFEJ73GBbsiknfggVbHKClZkQTqiFWB56E5fOpCM4ckbo9bqkoukpb+zJIZvE6qSDZFYC6fV3elNoz6TIeSebwFJ0D0rTQaSJdY0TvH2hFG+DKy1pV68FjX6gFPm7DpVonREH7RL9+YFhzq2ANoJTIDHRlQs+52rDRByXwZxZABHzWHOzljAVF4cQofj0kEa+OMm6v/h3DIUcclepilml6tBbrkyvwMNg8xwfWvkPRoUwSmf5vbUF+2o8Whi497FI13O3CEOhl0pBkE1aM7dfRHZVp5Q29JA2dI7n93LkEcMAJHAbe7FmW9cQVH03FF/RQxe8776aAjBha5kkMwburtBxtuqL0xYpbN+AfIj4ksFrT/+bDEE+UWttzWMY40LPwFX0VxeZ7njC/HoAPpxloSowVtd6VjRN5bPtK67uNYjgA8Wv1eVUA61x1W2TxAXnaEkEqgW50fGPxhMt7dcR2ARhpFQtVO6NIPn1AMXil1JpkGZ+VZu43Oqy1IpBdXC6eauHeb/0jP3Tj6zOVksoD7df2e3O5iHITOO8E4ERDjvTZHIeYsMhsGSr4='
        secret_access_key:
          secure: 'SiJb1KOrJ6Dsh+NSQnyhLqZLaBHrPuZrlVx0EXD9RMrhqdUGReE2uxHYJu6MiPZceFIUmAPcVqk7XFf1ZzutFoqCZ6/ijPYFHHF2+lissaLzkqoiG4ep6CTK6rk4Ymb320YR5PktY9Vg2sSgDw+bdqjMEpSbcX7MtoY0iqqn7toKe3B5KTLmKE1thUKfwXrnh11j8KgDQ4e/ErBk94sl9gR/GznmhMuIYtiKrE29TPZMRgHjtyk2L40KvXgD/Etz393mYEW6YSMxSztnQEayPZKSlpVb4RvZ125ftwdsj+RAl/JA/sHSpzzfbTLlfW/R+fIBRsqv79vydGo5vfOVcaf5FG706z4jnhN6U+jLM59WhAKCcCoUCDPzzAFocl86lR2wGZDVudkyWoKG2ojAw0rmlYo4iaA+yx8NKXljgv2LDehABUKaetUD0Fyqt6rnMqf3/ezUcK8SblNrVjRe4HmNjiW/t7q7HMIadUGLOU2o/qAAC/+vHaFiEjTTuqTD/sjEwpE3U8eUhdSo/iQQBYwL7eYR/voJzO9SyfAx/ji90Pm6j0KqZrzysnf/vt/gBzvamBrRQ9bC009cLfcA3YQFZOtE/rWVoi5k9xjESmYV+7rIplt5ZFlLpUg2G4hMYmLlOybCk/njIEMZUnwixP+fspBtyAg8NuYbeTChlJc='
