/**
 * Mark Down Component Wrapper.
 * Styles the HTML Elements generated by the "react-markdown" component
 */
import { WithTheme } from '@material-ui/core';
import * as React from 'react';
import { useCss } from 'src/helpers/useCss';
import { default as styled, StyledComponent } from 'styled-components';

type TStyledProps = {
  h2FontSize: string;
};

const StyledMarkdownWrapper: StyledComponent<
  'div',
  HTMLDivElement,
  TStyledProps,
  never
> = styled.div`
  p img {
    float: left;
    margin-right: 2em;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 3px 1px;
    width: 24vw;
    max-width: 250px;
  }

  a {
    color: ${(p: WithTheme): string => p.theme.palette.secondary.dark};
    text-decoration: none;
  }

  h1,
  h2 {
    font-size: ${(p: TStyledProps & WithTheme): string => p.h2FontSize};
  }

  em {
    font-weight: bold;
  }
`;

type TProps = React.ComponentProps<'div'>;

const MarkdownWrapper: React.FunctionComponent<TProps> = (): JSX.Element => {
  const h2FontSize: string = useCss('5vw', '1.5em', '425px');

  return <StyledMarkdownWrapper h2FontSize={h2FontSize} />;
};

export { MarkdownWrapper };
