version: '3'
services:
  cms:
    image: strapi/strapi
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_SSL: false
    volumes:
      - type: volume
        source: strapi
        target: /srv/app
        volume:
          nocopy: true
    ports:
      - '1337'
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata
        volume:
          nocopy: true
    ports:
      - '5432'
volumes:
  pgdata:
  strapi:
