version: '3.7'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host

  strapi:
    env_file: ./strapi/.env
    build:
      context: './strapi/'
    restart: always
    volumes:
      - type: bind
        source: ./strapi/src
        target: /srv/app
    ports:
      - target: 1337
        published: 1337
        protocol: tcp
        mode: host

volumes:
  pgdata:
