fragment preloadHomePage on HomePage {
  _id
  _contentTypeName
}

fragment preloadGenericPage on GenericPage {
  _id
  _contentTypeName
}

fragment preloadInstallAppPage on InstallAppPage {
  _id
  _contentTypeName
}

fragment preloadNewsPage on NewsPage {
  _id
  _contentTypeName
}

query getTheme($images: TSImagesConfig) {
  getTheme {
    headerMenu {
      menuEntries {
        _id
        page {
          ...preloadHomePage
          ...preloadGenericPage
          ...preloadInstallAppPage
          ...preloadNewsPage
        }
        subMenuEntries {
          _id
          page {
            ...preloadHomePage
            ...preloadGenericPage
            ...preloadInstallAppPage
            ...preloadNewsPage
          }
          subMenuEntries {
            _id
            page {
              ...preloadHomePage
              ...preloadGenericPage
              ...preloadInstallAppPage
              ...preloadNewsPage
            }
          }
        }
      }
    }
    photoPortrait {
      description
      path
      title
    }
    photoLandscape {
      description
      path
      title
    }
    footerInfoHtml(images: $images)
  }
}
