query getTheme {
  theme {
    headerMenu {
      label
      menuEntries {
        _id
        label
        url
      }
    }
    photoPortrait {
      description
      path
      title
    }
    photoLandscape {
      description
      path
      title
    }
    overlay
    footerIconLinks {
      icon {
        description
        path
        title
      }
      link
    }
    footerInfo
  }
}
