fragment GenericPage on GenericPage {
  _id
  _contentTypeName
  url
}

fragment HomePage on HomePage {
  _id
  _contentTypeName
  url
}

query getTheme($images: TSImagesConfig) {
  theme {
    headerMenu {
      label
      menuEntries {
        _id
        label
        url
        page {
          ...GenericPage
          ...HomePage
        }
        subMenuEntries {
          _id
          label
          url
          page {
            ...GenericPage
            ...HomePage
          }
          subMenuEntries {
            _id
            label
            url
            page {
              ...GenericPage
              ...HomePage
            }
          }
        }
      }
    }
    photoPortrait {
      description
      path
      title
    }
    photoLandscape {
      description
      path
      title
    }
    overlay
    footerIconLinks {
      icon {
        description
        path
        title
      }
      link
    }
    footerInfoHtml(images: $images)
  }
}
