query getTheme {
  theme {
    headerMenu {
      label
      menuEntries {
        _id
        label
        url
      }
    }
    footerIconLinks {
      icon {
        description
        path
        title
      }
      link
    }
    footerInfo
  }
}
